'use strict';
// Drafts the information request to the host of a night: English, a line of dashes, the
// traveller's own language (and the host's language on request), wherever the trip goes. The questions come from what the place's record does
// not answer yet. The draft is returned to the assistant, which must show it word for word
// to the user and wait for an explicit go before anyone sends it: nothing is ever sent here.
// The texts are the message itself, in the host's languages, not interface strings: they
// live here rather than in the 27 interface catalogues.
const contacts = require('./contacts');
const { findDay, stayOn } = require('./trip');
const placeInfo = require('./place-info');
const nightStatus = require('./night-status');
const { hhmm } = require('./util');
const { money } = require('./i18n');

const SEPARATOR = '————————————';
// Every language with a message template; English is always the first part.
const langsOf = () => Object.keys(TEXT);
const { locale } = require('./i18n');
// English dates in the international order (12 October), every other language its own.
const LOCALE = new Proxy({}, { get: (_, lg) => (lg === 'en' ? 'en-GB' : locale(String(lg))) });

class MessageError extends Error {}

// {placeholders}: dates, n (nights), people, dog, vehicle, size, time, price.
const TEXT = {
  en: {
    hello: 'Hello,',
    intro: 'We are planning a road trip and would like to stay with you {dates} ({n}).',
    party: 'We are {people}{dog}, travelling {vehicle}.',
    ask: 'Could you please tell us:',
    rooftop_tent: 'Do you accept a car with a rooftop tent (we sleep in the tent on the roof of the car, {size})?',
    van: 'Can we stay overnight in our {vehicleShort} ({size})?',
    dog: 'Is our dog welcome, and is there a supplement for it?',
    dog_fee: 'How much is the supplement for our dog?',
    open: 'Are you open {dates}?',
    arrival: 'We expect to arrive around {time}: is that fine?',
    arrival_hours: 'Until what time can we arrive?',
    price: 'What would the price be for {people}{dog} and our vehicle, for {n}?',
    price_confirm: 'Could you confirm the price of {price} for {people}{dog} and our vehicle, for {n}?',
    water: 'Is there drinking water to fill our tank?',
    electricity: 'Is an electric hook-up available, and at what price?',
    notBooking: 'This is a request for information, not a booking yet: we will confirm once we have your answer.',
    thanks: 'Thank you very much,',
    subject: 'Information request',
    night: ['night', 'nights'],
    person: ['1 person', '{k} people'],
    withDog: ' with a dog',
    rooftop: 'by car with a rooftop tent',
    campervan: 'in a campervan',
    motorhome: 'in a motorhome',
    campervanShort: 'campervan',
    motorhomeShort: 'motorhome',
    on: 'on {date}',
    fromTo: 'from {from} to {to}',
  },
  fr: {
    hello: 'Bonjour,',
    intro: 'Nous préparons un voyage en voiture et aimerions séjourner chez vous {dates} ({n}).',
    party: 'Nous sommes {people}{dog}, et voyageons {vehicle}.',
    ask: 'Pourriez-vous nous dire :',
    rooftop_tent: 'Acceptez-vous une voiture avec une tente de toit (nous dormons dans la tente, sur le toit de la voiture, {size}) ?',
    van: 'Pouvons-nous passer la nuit dans notre {vehicleShort} ({size}) ?',
    dog: 'Notre chien est-il le bienvenu, et y a-t-il un supplément ?',
    dog_fee: 'Quel est le montant du supplément pour notre chien ?',
    open: 'Êtes-vous ouverts {dates} ?',
    arrival: 'Nous pensons arriver vers {time} : cela vous convient-il ?',
    arrival_hours: "Jusqu'à quelle heure pouvons-nous arriver ?",
    price: 'Quel serait le prix pour {people}{dog} et notre véhicule, pour {n} ?',
    price_confirm: 'Pouvez-vous nous confirmer le prix de {price} pour {people}{dog} et notre véhicule, pour {n} ?',
    water: "Y a-t-il de l'eau potable pour remplir notre réservoir ?",
    electricity: 'Un branchement électrique est-il possible, et à quel prix ?',
    notBooking: "Il s'agit d'une demande d'informations, pas encore d'une réservation : nous confirmerons après votre réponse.",
    thanks: 'Merci beaucoup,',
    subject: "Demande d'informations",
    night: ['nuit', 'nuits'],
    person: ['1 personne', '{k} personnes'],
    withDog: ' avec un chien',
    rooftop: 'en voiture avec une tente de toit',
    campervan: 'en van aménagé',
    motorhome: 'en camping-car',
    campervanShort: 'van aménagé',
    motorhomeShort: 'camping-car',
    on: 'le {date}',
    fromTo: 'du {from} au {to}',
  },
  it: {
    hello: 'Buongiorno,',
    intro: 'Stiamo organizzando un viaggio in auto e vorremmo soggiornare da voi {dates} ({n}).',
    party: 'Siamo {people}{dog} e viaggiamo {vehicle}.',
    ask: 'Potreste dirci:',
    rooftop_tent: "Accettate un'auto con tenda da tetto (dormiamo nella tenda sul tetto dell'auto, {size})?",
    van: 'Possiamo pernottare nel nostro {vehicleShort} ({size})?',
    dog: 'Il nostro cane è il benvenuto, e c’è un supplemento?',
    dog_fee: 'Quanto costa il supplemento per il nostro cane?',
    open: 'Siete aperti {dates}?',
    arrival: 'Pensiamo di arrivare verso le {time}: va bene?',
    arrival_hours: 'Fino a che ora possiamo arrivare?',
    price: 'Quale sarebbe il prezzo per {people}{dog} e il nostro veicolo, per {n}?',
    price_confirm: 'Potreste confermarci il prezzo di {price} per {people}{dog} e il nostro veicolo, per {n}?',
    water: "C'è acqua potabile per riempire il serbatoio?",
    electricity: "È disponibile un allacciamento elettrico, e a quale prezzo?",
    notBooking: 'Questa è una richiesta di informazioni, non ancora una prenotazione: confermeremo dopo la vostra risposta.',
    thanks: 'Grazie mille,',
    subject: 'Richiesta di informazioni',
    night: ['notte', 'notti'],
    person: ['1 persona', '{k} persone'],
    withDog: ' con un cane',
    rooftop: 'in auto con tenda da tetto',
    campervan: 'in camper van',
    motorhome: 'in camper',
    campervanShort: 'camper van',
    motorhomeShort: 'camper',
    on: 'il {date}',
    fromTo: 'dal {from} al {to}',
  },
  de: {
    hello: 'Guten Tag,',
    intro: 'Wir planen eine Reise mit dem Auto und würden gerne bei Ihnen übernachten, {dates} ({n}).',
    party: 'Wir sind {people}{dog} und reisen {vehicle}.',
    ask: 'Könnten Sie uns bitte sagen:',
    rooftop_tent: 'Akzeptieren Sie ein Auto mit Dachzelt (wir schlafen im Zelt auf dem Autodach, {size})?',
    van: 'Dürfen wir in unserem {vehicleShort} übernachten ({size})?',
    dog: 'Ist unser Hund willkommen, und gibt es einen Aufpreis?',
    dog_fee: 'Wie hoch ist der Aufpreis für unseren Hund?',
    open: 'Haben Sie {dates} geöffnet?',
    arrival: 'Wir kommen voraussichtlich gegen {time} Uhr an: passt das?',
    arrival_hours: 'Bis wann können wir ankommen?',
    price: 'Was würde es für {people}{dog} und unser Fahrzeug kosten, für {n}?',
    price_confirm: 'Können Sie uns den Preis von {price} für {people}{dog} und unser Fahrzeug bestätigen, für {n}?',
    water: 'Gibt es Trinkwasser, um unseren Tank zu füllen?',
    electricity: 'Gibt es einen Stromanschluss, und zu welchem Preis?',
    notBooking: 'Dies ist eine Anfrage, noch keine Buchung: Wir bestätigen nach Ihrer Antwort.',
    thanks: 'Vielen Dank,',
    subject: 'Anfrage',
    night: ['Nacht', 'Nächte'],
    person: ['1 Person', '{k} Personen'],
    withDog: ' mit Hund',
    rooftop: 'mit dem Auto und einem Dachzelt',
    campervan: 'mit einem Campervan',
    motorhome: 'mit einem Wohnmobil',
    campervanShort: 'Campervan',
    motorhomeShort: 'Wohnmobil',
    on: 'am {date}',
    fromTo: 'vom {from} bis {to}',
  },
  es: {
    hello: 'Buenos días:',
    intro: 'Estamos preparando un viaje en coche y nos gustaría alojarnos en su establecimiento {dates} ({n}).',
    party: 'Somos {people}{dog} y viajamos {vehicle}.',
    ask: '¿Podrían indicarnos lo siguiente?',
    rooftop_tent: '¿Aceptan un coche con tienda de techo (dormimos en la tienda, sobre el techo del coche, {size})?',
    van: '¿Podemos pasar la noche en nuestra {vehicleShort} ({size})?',
    dog: '¿Admiten a nuestro perro? ¿Hay algún suplemento?',
    dog_fee: '¿Cuánto es el suplemento por nuestro perro?',
    open: '¿Están abiertos {dates}?',
    arrival: 'Calculamos llegar hacia las {time}: ¿les parece bien?',
    arrival_hours: '¿Hasta qué hora podemos llegar?',
    price: '¿Cuál sería el precio para {people}{dog} y nuestro vehículo, por {n}?',
    price_confirm: '¿Podrían confirmarnos el precio de {price} para {people}{dog} y nuestro vehículo, por {n}?',
    water: '¿Hay agua potable para llenar nuestro depósito?',
    electricity: '¿Disponen de toma eléctrica, y a qué precio?',
    notBooking: 'Se trata de una solicitud de información, todavía no de una reserva: confirmaremos cuando tengamos su respuesta.',
    thanks: 'Muchas gracias,',
    subject: 'Solicitud de información',
    night: ['noche', 'noches'],
    person: ['1 persona', '{k} personas'],
    withDog: ' con un perro',
    rooftop: 'en coche con tienda de techo',
    campervan: 'en furgoneta camper',
    motorhome: 'en autocaravana',
    campervanShort: 'furgoneta camper',
    motorhomeShort: 'autocaravana',
    on: 'el {date}',
    fromTo: 'del {from} al {to}',
  },
  ca: {
    hello: 'Bon dia,',
    intro: 'Estem preparant un viatge en cotxe i ens agradaria allotjar-nos al seu establiment {dates} ({n}).',
    party: 'Som {people}{dog} i viatgem {vehicle}.',
    ask: 'Ens podrien indicar:',
    rooftop_tent: 'Accepten un cotxe amb tenda de sostre (dormim a la tenda, sobre el sostre del cotxe, {size})?',
    van: 'Podem passar la nit a la nostra {vehicleShort} ({size})?',
    dog: 'El nostre gos hi és benvingut? Hi ha algun suplement?',
    dog_fee: 'Quin és el suplement per al nostre gos?',
    open: 'Estan oberts {dates}?',
    arrival: 'Pensem arribar cap a les {time}: els va bé?',
    arrival_hours: 'Fins a quina hora podem arribar?',
    price: 'Quin seria el preu per a {people}{dog} i el nostre vehicle, per {n}?',
    price_confirm: 'Ens podrien confirmar el preu de {price} per a {people}{dog} i el nostre vehicle, per {n}?',
    water: 'Hi ha aigua potable per omplir el nostre dipòsit?',
    electricity: 'Hi ha connexió elèctrica, i a quin preu?',
    notBooking: 'És una sol·licitud d’informació, encara no una reserva: confirmarem quan tinguem la seva resposta.',
    thanks: 'Moltes gràcies,',
    subject: 'Sol·licitud d’informació',
    night: ['nit', 'nits'],
    person: ['1 persona', '{k} persones'],
    withDog: ' amb un gos',
    rooftop: 'en cotxe amb tenda de sostre',
    campervan: 'en furgoneta camper',
    motorhome: 'en autocaravana',
    campervanShort: 'furgoneta camper',
    motorhomeShort: 'autocaravana',
    on: 'el {date}',
    fromTo: 'del {from} al {to}',
  },
  br: {
    hello: 'Olá,',
    intro: 'Estamos planejando uma viagem de carro e gostaríamos de nos hospedar com vocês {dates} ({n}).',
    party: 'Somos {people}{dog} e viajamos {vehicle}.',
    ask: 'Vocês poderiam nos informar:',
    rooftop_tent: 'Vocês aceitam um carro com barraca de teto (dormimos na barraca, em cima do carro, {size})?',
    van: 'Podemos passar a noite {vehicleShort} ({size})?',
    dog: 'Nosso cachorro é bem-vindo? Há alguma taxa extra?',
    dog_fee: 'Qual é a taxa extra para o nosso cachorro?',
    open: 'Vocês estarão abertos {dates}?',
    arrival: 'Pretendemos chegar por volta das {time}: tudo bem?',
    arrival_hours: 'Até que horas podemos chegar?',
    price: 'Qual seria o valor para {people}{dog} e o nosso veículo, por {n}?',
    price_confirm: 'Vocês poderiam confirmar o valor de {price} para {people}{dog} e o nosso veículo, por {n}?',
    water: 'Há água potável para encher o nosso reservatório?',
    electricity: 'Há ponto de energia elétrica, e qual é o valor?',
    notBooking: 'Este é um pedido de informações, ainda não uma reserva: confirmaremos depois da resposta de vocês.',
    thanks: 'Agradecemos desde já,',
    subject: 'Pedido de informações',
    night: ['noite', 'noites'],
    person: ['1 pessoa', '{k} pessoas'],
    withDog: ' com um cachorro',
    rooftop: 'de carro com barraca de teto',
    campervan: 'de van adaptada',
    motorhome: 'de motorhome',
    campervanShort: 'na nossa van adaptada',
    motorhomeShort: 'no nosso motorhome',
    on: 'em {date}',
    fromTo: 'de {from} a {to}',
  },
  nl: {
    hello: 'Goedendag,',
    intro: 'Wij plannen een reis met de auto en zouden graag bij u overnachten {dates} ({n}).',
    party: 'We zijn met {people}{dog} en reizen {vehicle}.',
    ask: 'Kunt u ons laten weten:',
    rooftop_tent: 'Accepteert u een auto met daktent (wij slapen in de tent op het dak van de auto, {size})?',
    van: 'Mogen wij overnachten in onze {vehicleShort} ({size})?',
    dog: 'Is onze hond welkom, en is er een toeslag?',
    dog_fee: 'Hoeveel bedraagt de toeslag voor onze hond?',
    open: 'Bent u {dates} geopend?',
    arrival: 'We verwachten rond {time} aan te komen: is dat goed?',
    arrival_hours: 'Tot hoe laat kunnen we aankomen?',
    price: 'Wat zou de prijs zijn voor {people}{dog} en ons voertuig, voor {n}?',
    price_confirm: 'Kunt u de prijs van {price} voor {people}{dog} en ons voertuig bevestigen, voor {n}?',
    water: 'Is er drinkwater om onze tank te vullen?',
    electricity: 'Is er een stroomaansluiting, en wat kost die?',
    notBooking: 'Dit is een verzoek om informatie, nog geen reservering: we bevestigen zodra we uw antwoord hebben.',
    thanks: 'Hartelijk dank,',
    subject: 'Informatieaanvraag',
    night: ['nacht', 'nachten'],
    person: ['1 persoon', '{k} personen'],
    withDog: ' en een hond',
    rooftop: 'met de auto en een daktent',
    campervan: 'met een campervan',
    motorhome: 'met een camper',
    campervanShort: 'campervan',
    motorhomeShort: 'camper',
    on: 'op {date}',
    fromTo: 'van {from} tot {to}',
  },
  sv: {
    hello: 'Hej,',
    intro: 'Vi planerar en bilresa och skulle gärna vilja övernatta hos er {dates} ({n}).',
    party: 'Vi är {people}{dog} och reser {vehicle}.',
    ask: 'Skulle ni kunna berätta:',
    rooftop_tent: 'Tar ni emot en bil med taktält (vi sover i tältet på biltaket, {size})?',
    van: 'Får vi övernatta i vår {vehicleShort} ({size})?',
    dog: 'Är vår hund välkommen, och tillkommer någon avgift?',
    dog_fee: 'Hur mycket kostar tillägget för vår hund?',
    open: 'Har ni öppet {dates}?',
    arrival: 'Vi räknar med att komma fram runt {time}: går det bra?',
    arrival_hours: 'Hur sent kan vi komma fram?',
    price: 'Vad skulle priset bli för {people}{dog} och vårt fordon, för {n}?',
    price_confirm: 'Kan ni bekräfta priset {price} för {people}{dog} och vårt fordon, för {n}?',
    water: 'Finns det dricksvatten så att vi kan fylla vår tank?',
    electricity: 'Finns det elanslutning, och vad kostar den?',
    notBooking: 'Det här är en förfrågan, ännu ingen bokning: vi bekräftar när vi har fått ert svar.',
    thanks: 'Tack så mycket,',
    subject: 'Förfrågan',
    night: ['natt', 'nätter'],
    person: ['1 person', '{k} personer'],
    withDog: ' och en hund',
    rooftop: 'med bil och taktält',
    campervan: 'med campervan',
    motorhome: 'med husbil',
    campervanShort: 'campervan',
    motorhomeShort: 'husbil',
    on: '{date}',
    fromTo: 'från {from} till {to}',
  },
  et: {
    hello: 'Tere,',
    intro: 'Planeerime autoreisi ja sooviksime ööbida Teie juures: {dates} ({n}).',
    party: 'Meid on {people}{dog} ja reisime {vehicle}.',
    ask: 'Palun andke meile teada:',
    rooftop_tent: 'Kas võtate vastu katusetelgiga auto (magame telgis auto katusel, {size})?',
    van: 'Kas saame ööbida oma {vehicleShort} ({size})?',
    dog: 'Kas meie koer on oodatud ja kas selle eest on lisatasu?',
    dog_fee: 'Kui suur on lisatasu meie koera eest?',
    open: 'Kas olete avatud: {dates}?',
    arrival: 'Plaanime saabuda umbes kell {time}: kas see sobib?',
    arrival_hours: 'Mis kellani saame saabuda?',
    price: 'Mis oleks hind meile ({people}{dog}) koos sõidukiga, kokku {n}?',
    price_confirm: 'Kas saate kinnitada hinna {price} meile ({people}{dog}) koos sõidukiga, kokku {n}?',
    water: 'Kas on joogivett, et oma paak täita?',
    electricity: 'Kas elektriühendus on saadaval ja mis see maksab?',
    notBooking: 'See on päring, mitte veel broneering: kinnitame pärast Teie vastust.',
    thanks: 'Suur aitäh,',
    subject: 'Päring',
    night: ['öö', 'ööd'],
    person: ['1 inimene', '{k} inimest'],
    withDog: ' ja koer',
    rooftop: 'katusetelgiga autoga',
    campervan: 'matkabussiga',
    motorhome: 'matkaautoga',
    campervanShort: 'matkabussis',
    motorhomeShort: 'matkaautos',
    on: '{date}',
    fromTo: '{from} – {to}',
  },
  hu: {
    hello: 'Jó napot kívánunk!',
    intro: 'Autós utazást tervezünk, és szívesen megszállnánk Önöknél a következő időpontban: {dates} ({n}).',
    party: 'Létszámunk {people}{dog}, és {vehicle} utazunk.',
    ask: 'Kérjük, tájékoztassanak a következőkről:',
    rooftop_tent: 'Fogadnak tetősátras autót (az autó tetején, a sátorban alszunk, {size})?',
    van: 'Eltölthetjük az éjszakát a {vehicleShort} ({size})?',
    dog: 'Szívesen látják a kutyánkat, és kell érte felárat fizetni?',
    dog_fee: 'Mennyi a felár a kutyánkért?',
    open: 'Nyitva lesznek ebben az időpontban: {dates}?',
    arrival: 'Várhatóan {time} körül érkezünk: megfelel ez Önöknek?',
    arrival_hours: 'Legkésőbb hány óráig érkezhetünk?',
    price: 'Mennyibe kerülne {n} számunkra ({people}{dog}), a járművel együtt?',
    price_confirm: 'Meg tudnák erősíteni, hogy {n} ára számunkra ({people}{dog}), a járművel együtt {price}?',
    water: 'Van ivóvíz, amellyel feltölthetjük a tartályunkat?',
    electricity: 'Van elektromos csatlakozási lehetőség, és mennyibe kerül?',
    notBooking: 'Ez csak információkérés, még nem foglalás: a válaszuk után visszaigazoljuk.',
    thanks: 'Köszönjük szépen,',
    subject: 'Információkérés',
    night: ['éjszaka', 'éjszaka'],
    person: ['1 fő', '{k} fő'],
    withDog: ', egy kutyával',
    rooftop: 'tetősátras autóval',
    campervan: 'lakóbusszal',
    motorhome: 'lakóautóval',
    campervanShort: 'lakóbuszunkban',
    motorhomeShort: 'lakóautónkban',
    on: '{date}',
    fromTo: '{from} – {to}',
  },
  cs: {
    hello: 'Dobrý den,',
    intro: 'Plánujeme cestu autem a rádi bychom u Vás přenocovali v tomto termínu: {dates} ({n}).',
    party: 'Jsme {people}{dog} a cestujeme {vehicle}.',
    ask: 'Mohli byste nám prosím sdělit:',
    rooftop_tent: 'Přijímáte auto se střešním stanem (spíme ve stanu na střeše auta, {size})?',
    van: 'Můžeme přenocovat {vehicleShort} ({size})?',
    dog: 'Je u Vás náš pes vítán a platí se za něj příplatek?',
    dog_fee: 'Jak vysoký je příplatek za našeho psa?',
    open: 'Máte v tomto termínu otevřeno: {dates}?',
    arrival: 'Předpokládáme příjezd kolem {time}: vyhovuje Vám to?',
    arrival_hours: 'Do kolika hodin můžeme přijet?',
    price: 'Jaká by byla cena za {n} pro nás ({people}{dog}) i s vozidlem?',
    price_confirm: 'Můžete nám potvrdit cenu {price} za {n} pro nás ({people}{dog}) i s vozidlem?',
    water: 'Je k dispozici pitná voda, abychom si mohli naplnit nádrž?',
    electricity: 'Je k dispozici přípojka elektřiny a za jakou cenu?',
    notBooking: 'Jde o nezávaznou poptávku, zatím ne o rezervaci: potvrdíme ji po Vaší odpovědi.',
    thanks: 'Děkujeme,',
    subject: 'Poptávka',
    night: ['noc', 'noci'],
    person: ['1 osoba', '{k} osoby'],
    withDog: ' a pes',
    rooftop: 'autem se střešním stanem',
    campervan: 'obytnou dodávkou',
    motorhome: 'obytným autem',
    campervanShort: 'v naší obytné dodávce',
    motorhomeShort: 'v našem obytném autě',
    on: '{date}',
    fromTo: '{from} – {to}',
  },
  sk: {
    hello: 'Dobrý deň,',
    intro: 'Plánujeme cestu autom a radi by sme u Vás prenocovali v tomto termíne: {dates} ({n}).',
    party: 'Sme {people}{dog} a cestujeme {vehicle}.',
    ask: 'Mohli by ste nám, prosím, povedať:',
    rooftop_tent: 'Prijímate auto so strešným stanom (spíme v stane na streche auta, {size})?',
    van: 'Môžeme prenocovať {vehicleShort} ({size})?',
    dog: 'Je u Vás náš pes vítaný a platí sa zaň príplatok?',
    dog_fee: 'Aký vysoký je príplatok za nášho psa?',
    open: 'Máte v tomto termíne otvorené: {dates}?',
    arrival: 'Predpokladáme príchod okolo {time}: vyhovuje Vám to?',
    arrival_hours: 'Do koľkej môžeme prísť?',
    price: 'Aká by bola cena za {n} pre nás ({people}{dog}) aj s vozidlom?',
    price_confirm: 'Môžete nám potvrdiť cenu {price} za {n} pre nás ({people}{dog}) aj s vozidlom?',
    water: 'Je k dispozícii pitná voda, aby sme si mohli naplniť nádrž?',
    electricity: 'Je k dispozícii elektrická prípojka a za akú cenu?',
    notBooking: 'Ide o nezáväznú žiadosť o informácie, zatiaľ nie o rezerváciu: potvrdíme ju po Vašej odpovedi.',
    thanks: 'Ďakujeme,',
    subject: 'Žiadosť o informácie',
    night: ['noc', 'noci'],
    person: ['1 osoba', '{k} osoby'],
    withDog: ' a pes',
    rooftop: 'autom so strešným stanom',
    campervan: 'obytnou dodávkou',
    motorhome: 'obytným autom',
    campervanShort: 'v našej obytnej dodávke',
    motorhomeShort: 'v našom obytnom aute',
    on: '{date}',
    fromTo: '{from} – {to}',
  },
  pl: {
    hello: 'Dzień dobry,',
    intro: 'Planujemy podróż samochodem i chcielibyśmy zatrzymać się u Państwa w terminie: {dates} ({n}).',
    party: 'Podróżujemy {vehicle}: {people}{dog}.',
    ask: 'Prosimy o informację:',
    rooftop_tent: 'Czy przyjmują Państwo samochód z namiotem dachowym (śpimy w namiocie na dachu samochodu, {size})?',
    van: 'Czy możemy przenocować {vehicleShort} ({size})?',
    dog: 'Czy nasz pies jest mile widziany i czy obowiązuje za niego dopłata?',
    dog_fee: 'Jaka jest dopłata za naszego psa?',
    open: 'Czy będą Państwo otwarci w tym terminie: {dates}?',
    arrival: 'Planujemy przyjazd około {time}: czy to Państwu odpowiada?',
    arrival_hours: 'Do której godziny możemy przyjechać?',
    price: 'Jaka byłaby cena za {n} dla nas ({people}{dog}) wraz z pojazdem?',
    price_confirm: 'Czy mogą Państwo potwierdzić cenę {price} za {n} dla nas ({people}{dog}) wraz z pojazdem?',
    water: 'Czy jest woda pitna, żebyśmy mogli napełnić nasz zbiornik?',
    electricity: 'Czy jest możliwość podłączenia prądu i ile to kosztuje?',
    notBooking: 'To jest zapytanie o informacje, jeszcze nie rezerwacja: potwierdzimy po otrzymaniu Państwa odpowiedzi.',
    thanks: 'Serdecznie dziękujemy,',
    subject: 'Zapytanie',
    night: ['noc', 'noce'],
    person: ['1 osoba', '{k} osoby'],
    withDog: ' i pies',
    rooftop: 'samochodem z namiotem dachowym',
    campervan: 'vanem kempingowym',
    motorhome: 'kamperem',
    campervanShort: 'w naszym vanie kempingowym',
    motorhomeShort: 'w naszym kamperze',
    on: '{date}',
    fromTo: '{from} – {to}',
  },
  ru: {
    hello: 'Здравствуйте!',
    intro: 'Мы планируем путешествие на автомобиле и хотели бы остановиться у Вас в эти даты: {dates} ({n}).',
    party: 'Нас {people}{dog}, мы путешествуем {vehicle}.',
    ask: 'Подскажите, пожалуйста:',
    rooftop_tent: 'Принимаете ли Вы автомобиль с палаткой на крыше (мы спим в палатке на крыше машины, {size})?',
    van: 'Можно ли переночевать {vehicleShort} ({size})?',
    dog: 'Можно ли к Вам с собакой, и есть ли за неё доплата?',
    dog_fee: 'Какова доплата за собаку?',
    open: 'Вы работаете в эти даты: {dates}?',
    arrival: 'Мы планируем приехать около {time}: Вам это удобно?',
    arrival_hours: 'До какого времени можно приехать?',
    price: 'Какой будет цена за {n} для нас ({people}{dog}) вместе с машиной?',
    price_confirm: 'Можете ли Вы подтвердить цену {price} за {n} для нас ({people}{dog}) вместе с машиной?',
    water: 'Есть ли питьевая вода, чтобы наполнить наш бак?',
    electricity: 'Есть ли подключение к электричеству, и сколько оно стоит?',
    notBooking: 'Это запрос информации, а не бронирование: мы подтвердим после Вашего ответа.',
    thanks: 'Большое спасибо,',
    subject: 'Запрос информации',
    night: ['ночь', 'ночи'],
    person: ['1 человек', '{k} человека'],
    withDog: ' и собака',
    rooftop: 'на автомобиле с палаткой на крыше',
    campervan: 'на кемпервэне',
    motorhome: 'на автодоме',
    campervanShort: 'в нашем кемпервэне',
    motorhomeShort: 'в нашем автодоме',
    on: '{date}',
    fromTo: '{from} – {to}',
  },
  uk: {
    hello: 'Добрий день!',
    intro: 'Ми плануємо подорож автомобілем і хотіли б зупинитися у Вас у ці дати: {dates} ({n}).',
    party: 'Нас {people}{dog}, ми подорожуємо {vehicle}.',
    ask: 'Підкажіть, будь ласка:',
    rooftop_tent: 'Чи приймаєте Ви автомобіль із наметом на даху (ми спимо в наметі на даху машини, {size})?',
    van: 'Чи можна переночувати {vehicleShort} ({size})?',
    dog: 'Чи можна до Вас із собакою, і чи є за неї доплата?',
    dog_fee: 'Яка доплата за собаку?',
    open: 'Чи працюєте Ви в ці дати: {dates}?',
    arrival: 'Ми плануємо приїхати близько {time}: Вам це зручно?',
    arrival_hours: 'До котрої години можна приїхати?',
    price: 'Якою буде ціна за {n} для нас ({people}{dog}) разом з автомобілем?',
    price_confirm: 'Чи можете Ви підтвердити ціну {price} за {n} для нас ({people}{dog}) разом з автомобілем?',
    water: 'Чи є питна вода, щоб наповнити наш бак?',
    electricity: 'Чи є підключення до електрики, і скільки воно коштує?',
    notBooking: 'Це запит інформації, а не бронювання: ми підтвердимо після Вашої відповіді.',
    thanks: 'Щиро дякуємо,',
    subject: 'Запит інформації',
    night: ['ніч', 'ночі'],
    person: ['1 особа', '{k} особи'],
    withDog: ' і собака',
    rooftop: 'автомобілем із наметом на даху',
    campervan: 'кемпервеном',
    motorhome: 'автобудинком',
    campervanShort: 'в нашому кемпервені',
    motorhomeShort: 'в нашому автобудинку',
    on: '{date}',
    fromTo: '{from} – {to}',
  },
  gr: {
    hello: 'Γεια σας,',
    intro: 'Οργανώνουμε ένα ταξίδι με αυτοκίνητο και θα θέλαμε να διανυκτερεύσουμε στο κατάλυμά σας {dates} ({n}).',
    party: 'Είμαστε {people}{dog} και ταξιδεύουμε {vehicle}.',
    ask: 'Θα μπορούσατε να μας πείτε:',
    rooftop_tent: 'Δέχεστε αυτοκίνητο με σκηνή οροφής (κοιμόμαστε στη σκηνή, πάνω στην οροφή του αυτοκινήτου, {size});',
    van: 'Μπορούμε να διανυκτερεύσουμε στο {vehicleShort} ({size});',
    dog: 'Είναι ευπρόσδεκτος ο σκύλος μας, και υπάρχει επιπλέον χρέωση;',
    dog_fee: 'Πόση είναι η επιπλέον χρέωση για τον σκύλο μας;',
    open: 'Είστε ανοιχτά {dates};',
    arrival: 'Υπολογίζουμε να φτάσουμε γύρω στις {time}: σας εξυπηρετεί;',
    arrival_hours: 'Μέχρι τι ώρα μπορούμε να φτάσουμε;',
    price: 'Ποια θα ήταν η τιμή για {people}{dog} και το όχημά μας, για {n};',
    price_confirm: 'Μπορείτε να μας επιβεβαιώσετε την τιμή των {price} για {people}{dog} και το όχημά μας, για {n};',
    water: 'Υπάρχει πόσιμο νερό για να γεμίσουμε τη δεξαμενή μας;',
    electricity: 'Υπάρχει παροχή ρεύματος, και με ποια χρέωση;',
    notBooking: 'Πρόκειται για αίτημα πληροφοριών, όχι ακόμη για κράτηση: θα επιβεβαιώσουμε μόλις λάβουμε την απάντησή σας.',
    thanks: 'Σας ευχαριστούμε πολύ,',
    subject: 'Αίτημα πληροφοριών',
    night: ['νύχτα', 'νύχτες'],
    person: ['1 άτομο', '{k} άτομα'],
    withDog: ' με σκύλο',
    rooftop: 'με αυτοκίνητο και σκηνή οροφής',
    campervan: 'με κάμπερ βαν',
    motorhome: 'με αυτοκινούμενο τροχόσπιτο',
    campervanShort: 'κάμπερ βαν μας',
    motorhomeShort: 'αυτοκινούμενό μας',
    on: '{date}',
    fromTo: 'από {from} έως {to}',
  },
  tr: {
    hello: 'Merhaba,',
    intro: 'Arabayla bir yolculuk planlıyoruz ve şu tarihlerde sizde konaklamak istiyoruz: {dates} ({n}).',
    party: 'Grubumuz {people}{dog}; {vehicle} seyahat ediyoruz.',
    ask: 'Lütfen bize şunları bildirebilir misiniz:',
    rooftop_tent: 'Tavan çadırlı bir arabayı kabul ediyor musunuz (arabanın tavanındaki çadırda uyuyoruz, {size})?',
    van: 'Geceyi {vehicleShort} geçirebilir miyiz ({size})?',
    dog: 'Köpeğimizi kabul ediyor musunuz, bunun için ek ücret var mı?',
    dog_fee: 'Köpeğimiz için ek ücret ne kadar?',
    open: 'Bu tarihlerde açık mısınız: {dates}?',
    arrival: 'Saat {time} civarında varmayı planlıyoruz: sizin için uygun mu?',
    arrival_hours: 'En geç saat kaça kadar gelebiliriz?',
    price: 'Bizim ({people}{dog}) ve aracımız için {n} fiyatı ne olur?',
    price_confirm: 'Bizim ({people}{dog}) ve aracımız için {n} fiyatının {price} olduğunu teyit edebilir misiniz?',
    water: 'Depomuzu doldurmak için içme suyu var mı?',
    electricity: 'Elektrik bağlantısı var mı, ücreti ne kadar?',
    notBooking: 'Bu bir bilgi talebidir, henüz rezervasyon değildir: cevabınızı aldıktan sonra teyit edeceğiz.',
    thanks: 'Çok teşekkür ederiz,',
    subject: 'Bilgi talebi',
    night: ['gece', 'gece'],
    person: ['1 kişi', '{k} kişi'],
    withDog: ' ve bir köpek',
    rooftop: 'tavan çadırlı bir arabayla',
    campervan: 'kamp minibüsüyle',
    motorhome: 'karavanla',
    campervanShort: 'kamp minibüsümüzde',
    motorhomeShort: 'karavanımızda',
    on: '{date}',
    fromTo: '{from} – {to}',
  },
  az: {
    hello: 'Salam,',
    intro: 'Avtomobillə səyahət planlaşdırırıq və bu tarixlərdə sizdə qalmaq istərdik: {dates} ({n}).',
    party: 'Qrupumuz: {people}{dog}; {vehicle} səyahət edirik.',
    ask: 'Zəhmət olmasa, bizə bildirə bilərsinizmi:',
    rooftop_tent: 'Dam çadırlı avtomobil qəbul edirsinizmi (avtomobilin damındakı çadırda yatırıq, {size})?',
    van: 'Gecəni {vehicleShort} keçirə bilərikmi ({size})?',
    dog: 'İtimizi qəbul edirsinizmi və bunun üçün əlavə ödəniş varmı?',
    dog_fee: 'İtimiz üçün əlavə ödəniş nə qədərdir?',
    open: 'Bu tarixlərdə açıqsınızmı: {dates}?',
    arrival: 'Təxminən saat {time} radələrində çatmağı planlaşdırırıq: sizə uyğundurmu?',
    arrival_hours: 'Ən gec saat neçəyədək gələ bilərik?',
    price: 'Bizim ({people}{dog}) və avtomobilimiz üçün {n} qiyməti nə qədər olar?',
    price_confirm: 'Bizim ({people}{dog}) və avtomobilimiz üçün {n} qiymətinin {price} olduğunu təsdiq edə bilərsinizmi?',
    water: 'Su çənimizi doldurmaq üçün içməli su varmı?',
    electricity: 'Elektrik qoşulması varmı və qiyməti nə qədərdir?',
    notBooking: 'Bu, məlumat sorğusudur, hələ rezervasiya deyil: cavabınızı aldıqdan sonra təsdiq edəcəyik.',
    thanks: 'Çox sağ olun,',
    subject: 'Məlumat sorğusu',
    night: ['gecə', 'gecə'],
    person: ['1 nəfər', '{k} nəfər'],
    withDog: ' və bir it',
    rooftop: 'dam çadırlı avtomobillə',
    campervan: 'kemper furqonla',
    motorhome: 'avtoevlə',
    campervanShort: 'kemper furqonumuzda',
    motorhomeShort: 'avtoevimizdə',
    on: '{date}',
    fromTo: '{from} – {to}',
  },
  id: {
    hello: 'Halo Bapak/Ibu,',
    intro: 'Kami sedang merencanakan perjalanan dengan mobil dan ingin menginap di tempat Bapak/Ibu {dates} ({n}).',
    party: 'Kami {people}{dog}, bepergian {vehicle}.',
    ask: 'Mohon informasinya mengenai hal berikut:',
    rooftop_tent: 'Apakah Bapak/Ibu menerima mobil dengan tenda atap (kami tidur di tenda di atas atap mobil, {size})?',
    van: 'Bolehkah kami menginap di dalam {vehicleShort} kami ({size})?',
    dog: 'Apakah anjing kami diperbolehkan, dan apakah ada biaya tambahan?',
    dog_fee: 'Berapa biaya tambahan untuk anjing kami?',
    open: 'Apakah tempat Bapak/Ibu buka {dates}?',
    arrival: 'Kami perkirakan tiba sekitar pukul {time}: apakah tidak masalah?',
    arrival_hours: 'Sampai pukul berapa kami bisa tiba?',
    price: 'Berapa harganya untuk {people}{dog} dan kendaraan kami, selama {n}?',
    price_confirm: 'Bisakah Bapak/Ibu mengonfirmasi harga {price} untuk {people}{dog} dan kendaraan kami, selama {n}?',
    water: 'Apakah ada air minum untuk mengisi tangki kami?',
    electricity: 'Apakah tersedia sambungan listrik, dan berapa biayanya?',
    notBooking: 'Ini adalah permintaan informasi, belum pemesanan: kami akan mengonfirmasi setelah menerima jawaban Bapak/Ibu.',
    thanks: 'Terima kasih banyak,',
    subject: 'Permintaan informasi',
    night: ['malam', 'malam'],
    person: ['1 orang', '{k} orang'],
    withDog: ' dengan seekor anjing',
    rooftop: 'dengan mobil bertenda atap',
    campervan: 'dengan campervan',
    motorhome: 'dengan motorhome',
    campervanShort: 'campervan',
    motorhomeShort: 'motorhome',
    on: 'pada {date}',
    fromTo: 'dari {from} sampai {to}',
  },
  vi: {
    hello: 'Xin chào,',
    intro: 'Chúng tôi đang lên kế hoạch cho một chuyến đi bằng ô tô và muốn được nghỉ lại chỗ quý vị {dates} ({n}).',
    party: 'Chúng tôi gồm {people}{dog}, đi {vehicle}.',
    ask: 'Quý vị có thể cho chúng tôi biết:',
    rooftop_tent: 'Quý vị có nhận ô tô có lều trên nóc không (chúng tôi ngủ trong lều trên nóc xe, {size})?',
    van: 'Chúng tôi có thể ngủ qua đêm trong {vehicleShort} của mình không ({size})?',
    dog: 'Quý vị có nhận chó không, và có phụ phí không?',
    dog_fee: 'Phụ phí cho chó của chúng tôi là bao nhiêu?',
    open: 'Quý vị có mở cửa {dates} không?',
    arrival: 'Chúng tôi dự kiến đến khoảng {time}: như vậy có được không?',
    arrival_hours: 'Chúng tôi có thể đến muộn nhất lúc mấy giờ?',
    price: 'Giá cho {people}{dog} và xe của chúng tôi, trong {n}, là bao nhiêu?',
    price_confirm: 'Quý vị có thể xác nhận giá {price} cho {people}{dog} và xe của chúng tôi, trong {n}, được không?',
    water: 'Có nước uống để chúng tôi đổ đầy bình chứa không?',
    electricity: 'Có chỗ cắm điện không, và giá bao nhiêu?',
    notBooking: 'Đây là yêu cầu thông tin, chưa phải đặt chỗ: chúng tôi sẽ xác nhận sau khi nhận được phản hồi của quý vị.',
    thanks: 'Xin cảm ơn quý vị,',
    subject: 'Yêu cầu thông tin',
    night: ['đêm', 'đêm'],
    person: ['1 người', '{k} người'],
    withDog: ' và một chú chó',
    rooftop: 'bằng ô tô có lều trên nóc',
    campervan: 'bằng xe van cắm trại',
    motorhome: 'bằng xe nhà di động',
    campervanShort: 'xe van cắm trại',
    motorhomeShort: 'xe nhà di động',
    on: 'vào {date}',
    fromTo: 'từ {from} đến {to}',
  },
  th: {
    hello: 'สวัสดีครับ/ค่ะ',
    intro: 'เรากำลังวางแผนเดินทางด้วยรถยนต์ และอยากขอเข้าพักที่ของท่าน {dates} ({n})',
    party: 'เรามี {people}{dog} เดินทาง{vehicle}',
    ask: 'รบกวนช่วยแจ้งข้อมูลต่อไปนี้:',
    rooftop_tent: 'ท่านรับรถยนต์ที่มีเต็นท์บนหลังคาหรือไม่ (เรานอนในเต็นท์บนหลังคารถ ขนาด {size})',
    van: 'เราสามารถค้างคืนใน{vehicleShort}ของเราได้หรือไม่ (ขนาด {size})',
    dog: 'สุนัขของเราเข้าพักได้หรือไม่ และมีค่าบริการเพิ่มเติมหรือไม่',
    dog_fee: 'ค่าบริการเพิ่มเติมสำหรับสุนัขของเราเท่าไร',
    open: 'ท่านเปิดให้บริการ{dates} หรือไม่',
    arrival: 'เราคาดว่าจะถึงประมาณ {time} น. สะดวกหรือไม่',
    arrival_hours: 'เราสามารถมาถึงได้ช้าที่สุดกี่โมง',
    price: 'ราคาสำหรับ {people}{dog} และรถของเรา {n} เท่าไร',
    price_confirm: 'ช่วยยืนยันราคา {price} สำหรับ {people}{dog} และรถของเรา {n} ได้หรือไม่',
    water: 'มีน้ำดื่มให้เติมถังน้ำของเราหรือไม่',
    electricity: 'มีจุดเสียบปลั๊กไฟหรือไม่ และราคาเท่าไร',
    notBooking: 'ข้อความนี้เป็นการสอบถามข้อมูลเท่านั้น ยังไม่ใช่การจอง เราจะยืนยันอีกครั้งหลังจากได้รับคำตอบจากท่าน',
    thanks: 'ขอบคุณมากครับ/ค่ะ',
    subject: 'สอบถามข้อมูล',
    night: ['คืน', 'คืน'],
    person: ['1 คน', '{k} คน'],
    withDog: ' กับสุนัข 1 ตัว',
    rooftop: 'ด้วยรถยนต์ที่มีเต็นท์บนหลังคา',
    campervan: 'ด้วยรถตู้แคมป์ปิ้ง',
    motorhome: 'ด้วยรถบ้าน',
    campervanShort: 'รถตู้แคมป์ปิ้ง',
    motorhomeShort: 'รถบ้าน',
    on: 'ใน{date}',
    fromTo: 'ตั้งแต่{from} ถึง{to}',
  },
  ja: {
    hello: 'こんにちは。',
    intro: '車での旅行を計画しており、貴施設に宿泊させていただきたいと考えております。日程：{dates}（{n}）',
    party: '人数は{people}{dog}で、{vehicle}旅行しています。',
    ask: '以下について教えていただけますでしょうか。',
    rooftop_tent: 'ルーフテント付きの車でも利用できますでしょうか（車の屋根の上のテントで就寝します。{size}）。',
    van: '{vehicleShort}（{size}）での車中泊は可能でしょうか。',
    dog: '犬を連れて行っても大丈夫でしょうか。また、追加料金はかかりますか。',
    dog_fee: '犬の追加料金はおいくらでしょうか。',
    open: '{dates}は営業されていますか。',
    arrival: '{time}頃に到着する予定ですが、よろしいでしょうか。',
    arrival_hours: '何時までに到着すればよろしいでしょうか。',
    price: '{people}{dog}と車1台で{n}の場合、料金はおいくらになりますか。',
    price_confirm: '{people}{dog}と車1台で{n}の料金が{price}で間違いないか、ご確認いただけますでしょうか。',
    water: 'タンクに給水できる飲料水はありますか。',
    electricity: '電源は利用できますでしょうか。また、料金はおいくらですか。',
    notBooking: 'こちらはお問い合わせであり、まだ予約ではありません。お返事を拝見してから、改めて確定のご連絡をいたします。',
    thanks: 'どうぞよろしくお願いいたします。',
    subject: 'お問い合わせ',
    night: ['{k}泊', '{k}泊'],
    person: ['1名', '{k}名'],
    withDog: '・犬1匹',
    rooftop: 'ルーフテントを載せた車で',
    campervan: 'キャンピングバンで',
    motorhome: 'キャンピングカーで',
    campervanShort: 'キャンピングバン',
    motorhomeShort: 'キャンピングカー',
    on: '{date}',
    fromTo: '{from}から{to}まで',
  },
  ko: {
    hello: '안녕하세요.',
    intro: '자동차 여행을 계획하고 있으며, 귀 숙소에 묵고 싶습니다. 일정: {dates} ({n})',
    party: '인원은 {people}{dog}이며, {vehicle} 여행합니다.',
    ask: '다음 사항을 알려 주실 수 있을까요?',
    rooftop_tent: '루프탑 텐트를 단 차량도 이용할 수 있을까요(차 지붕 위의 텐트에서 잡니다, {size})?',
    van: '저희 {vehicleShort}에서 차박을 해도 될까요({size})?',
    dog: '반려견을 데려가도 될까요? 추가 요금이 있나요?',
    dog_fee: '반려견 추가 요금은 얼마인가요?',
    open: '{dates}에 영업하시나요?',
    arrival: '{time}쯤 도착할 예정인데 괜찮을까요?',
    arrival_hours: '몇 시까지 도착하면 될까요?',
    price: '{people}{dog}, 차량 1대, {n} 기준 요금은 얼마인가요?',
    price_confirm: '{people}{dog}, 차량 1대, {n} 기준 요금이 {price} 맞는지 확인 부탁드립니다.',
    water: '물탱크를 채울 수 있는 식수가 있나요?',
    electricity: '전기 연결이 가능한가요? 요금은 얼마인가요?',
    notBooking: '이 메시지는 문의일 뿐 아직 예약이 아닙니다. 답변을 받은 후 예약 여부를 확정하겠습니다.',
    thanks: '감사합니다.',
    subject: '문의',
    night: ['{k}박', '{k}박'],
    person: ['1명', '{k}명'],
    withDog: ', 반려견 1마리',
    rooftop: '루프탑 텐트를 단 차로',
    campervan: '캠핑밴으로',
    motorhome: '캠핑카로',
    campervanShort: '캠핑밴',
    motorhomeShort: '캠핑카',
    on: '{date}',
    fromTo: '{from} ~ {to}',
  },
  zh: {
    hello: '您好！',
    intro: '我们正在计划一次自驾旅行，希望能在贵处入住，日期：{dates}（{n}）。',
    party: '我们一行{people}{dog}，{vehicle}出行。',
    ask: '想请教以下几个问题：',
    rooftop_tent: '是否接受带车顶帐篷的汽车（我们睡在车顶的帐篷里，车辆尺寸 {size}）？',
    van: '我们可以在自己的{vehicleShort}里过夜吗（{size}）？',
    dog: '可以带狗入住吗？是否需要额外收费？',
    dog_fee: '我们的狗需要额外支付多少费用？',
    open: '{dates}是否营业？',
    arrival: '我们预计{time}左右到达，可以吗？',
    arrival_hours: '最晚几点可以到达？',
    price: '{people}{dog}及一辆车，住{n}，费用是多少？',
    price_confirm: '能否确认{people}{dog}及一辆车，住{n}，费用为{price}？',
    water: '是否有饮用水可以给我们的水箱加水？',
    electricity: '是否提供电源接口？费用是多少？',
    notBooking: '这只是咨询，并非预订：收到您的回复后我们再确认。',
    thanks: '非常感谢！',
    subject: '咨询',
    night: ['{k}晚', '{k}晚'],
    person: ['1人', '{k}人'],
    withDog: '和一只狗',
    rooftop: '开一辆带车顶帐篷的汽车',
    campervan: '开露营车',
    motorhome: '开房车',
    campervanShort: '露营车',
    motorhomeShort: '房车',
    on: '{date}',
    fromTo: '{from}至{to}',
  },
  'zh-TW': {
    hello: '您好：',
    intro: '我們正在規劃一趟自駕旅行，希望能入住貴處，日期：{dates}（{n}）。',
    party: '我們一行{people}{dog}，{vehicle}旅行。',
    ask: '想請教以下幾個問題：',
    rooftop_tent: '是否接受加裝車頂帳篷的汽車（我們睡在車頂的帳篷裡，車輛尺寸 {size}）？',
    van: '我們可以在自己的{vehicleShort}裡過夜嗎（{size}）？',
    dog: '可以帶狗入住嗎？是否需要另外收費？',
    dog_fee: '我們的狗需要另外支付多少費用？',
    open: '{dates}是否有營業？',
    arrival: '我們預計{time}左右抵達，方便嗎？',
    arrival_hours: '最晚幾點可以抵達？',
    price: '{people}{dog}及一輛車，住{n}，費用是多少？',
    price_confirm: '能否確認{people}{dog}及一輛車，住{n}，費用為{price}？',
    water: '是否有飲用水可以補充我們的水箱？',
    electricity: '是否提供電源插座？費用是多少？',
    notBooking: '這只是詢問，並非預訂：收到您的回覆後我們再確認。',
    thanks: '非常感謝！',
    subject: '詢問',
    night: ['{k}晚', '{k}晚'],
    person: ['1人', '{k}人'],
    withDog: '和一隻狗',
    rooftop: '開著加裝車頂帳篷的汽車',
    campervan: '開露營廂型車',
    motorhome: '開露營車',
    campervanShort: '露營廂型車',
    motorhomeShort: '露營車',
    on: '{date}',
    fromTo: '{from}至{to}',
  },
  ar: {
    hello: 'مرحبًا،',
    intro: 'نخطط لرحلة بالسيارة ونود الإقامة لديكم {dates} ({n}).',
    party: 'نحن {people}{dog}، ونسافر {vehicle}.',
    ask: 'هل يمكنكم إخبارنا بما يلي:',
    rooftop_tent: 'هل تقبلون سيارة مزودة بخيمة على السقف (ننام في الخيمة فوق سقف السيارة، {size})؟',
    van: 'هل يمكننا المبيت في {vehicleShort} ({size})؟',
    dog: 'هل يُسمح بكلبنا، وهل توجد رسوم إضافية؟',
    dog_fee: 'كم تبلغ الرسوم الإضافية لكلبنا؟',
    open: 'هل أنتم مفتوحون {dates}؟',
    arrival: 'نتوقع الوصول نحو الساعة {time}: هل يناسبكم ذلك؟',
    arrival_hours: 'حتى أي ساعة يمكننا الوصول؟',
    price: 'كم سيكون السعر لـ {people}{dog} ومركبتنا، مقابل {n}؟',
    price_confirm: 'هل يمكنكم تأكيد السعر البالغ {price} لـ {people}{dog} ومركبتنا، مقابل {n}؟',
    water: 'هل تتوفر مياه شرب لملء خزاننا؟',
    electricity: 'هل تتوفر وصلة كهرباء، وبأي سعر؟',
    notBooking: 'هذا طلب استفسار وليس حجزًا بعد: سنؤكد بعد تلقي ردكم.',
    thanks: 'شكرًا جزيلًا،',
    subject: 'طلب استفسار',
    night: ['ليلة واحدة', '{k} ليالٍ'],
    person: ['شخص واحد', '{k} أشخاص'],
    withDog: ' مع كلب',
    rooftop: 'بسيارة مزودة بخيمة على السقف',
    campervan: 'بعربة تخييم',
    motorhome: 'بمنزل متنقل',
    campervanShort: 'عربة التخييم الخاصة بنا',
    motorhomeShort: 'المنزل المتنقل الخاص بنا',
    on: 'يوم {date}',
    fromTo: 'من {from} إلى {to}',
  },
};

const fill = (tpl, p) => tpl.replace(/\{(\w+)\}/g, (_, k) => (p[k] == null ? '' : String(p[k])));

function dateText(iso, lg) {
  return new Intl.DateTimeFormat(LOCALE[lg], { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${iso}T12:00:00Z`));
}

/** The questions the record leaves open, in order: [{ key, params }]. */
function questionsFor(info, settings, ctxt) {
  const am = (info && info.amenities) || {};
  const q = [];
  if (settings.vehicle === 'rooftop_tent') { if (am.rooftop_tent !== 'yes') q.push('rooftop_tent'); } else q.push('van');
  if (settings.dog) {
    if (am.dog === 'fee' && (!info || info.dog_fee == null)) q.push('dog_fee');
    else if (am.dog !== 'yes' && am.dog !== 'fee') q.push('dog');
  }
  q.push('open');
  q.push(ctxt.arrival != null ? 'arrival' : 'arrival_hours');
  q.push(ctxt.price != null ? 'price_confirm' : 'price');
  if (am.water !== 'yes') q.push('water');
  if (settings.vehicle !== 'rooftop_tent' && am.electricity !== 'yes') q.push('electricity');
  return q;
}

function body(lg, keys, p, extraQuestions) {
  const T = TEXT[lg];
  const lines = [T.hello, '', fill(T.intro, p), fill(T.party, p), '', T.ask];
  const all = keys.map((k) => fill(T[k], p));
  // Questions the assistant adds are written by it in English; they go in the English part.
  if (lg === 'en') all.push(...extraQuestions);
  all.forEach((x, i) => lines.push(`${i + 1}. ${x}`));
  lines.push('', T.notBooking, '', T.thanks);
  if (p.signature) lines.push(p.signature);
  return lines.join('\n');
}

function params(lg, base) {
  const T = TEXT[lg];
  // Counts in the language's own digits (Arabic), like the dates around them.
  const dec = (x) => new Intl.NumberFormat(LOCALE[lg], { maximumFractionDigits: 2 }).format(x);
  // Night forms with {k} place the number themselves (CJK counters: 2泊, 2박; Arabic "one night" in words); otherwise "2 nights".
  const nightWord = T.night[base.nights > 1 ? 1 : 0];
  const n = T.night[1].includes('{k}') ? fill(nightWord, { k: dec(base.nights) }) : `${dec(base.nights)} ${nightWord}`;
  const dates = base.end ? fill(T.fromTo, { from: dateText(base.start, lg), to: dateText(base.end, lg) }) : fill(T.on, { date: dateText(base.start, lg) });
  const people = fill(T.person[base.travellers > 1 ? 1 : 0], { k: dec(base.travellers) });
  return {
    ...base, n, dates, people, size: `${dec(base.length)} m × ${dec(base.height)} m`, dog: base.dog ? T.withDog : '',
    vehicle: T[base.vehicle === 'rooftop_tent' ? 'rooftop' : base.vehicle],
    vehicleShort: T[`${base.vehicle}Short`],
    price: base.price == null ? null : money(base.price, base.currency, lg),
  };
}

/**
 * a: { placeId, dayNumber?, dayId?, nights?, arrival?, extra_questions?, language_extra?, signature? }
 * → { to, otherChannels, subject, text, questions, reminder }
 */
function draft(model, settings, a) {
  const place = model.poolById.get(a.placeId);
  if (!place) throw new MessageError(`place ${a.placeId} is not in trip ${model.tripId}`);
  // The evening asked, else the place's first planned stay. On a later evening of a stay of
  // this place, the message is about the whole stay, from its first evening.
  const asked = findDay(model, { dayId: a.dayId, dayNumber: a.dayNumber });
  if ((a.dayId != null || a.dayNumber != null) && !asked) throw new MessageError(`day ${a.dayNumber ?? a.dayId} is not in trip ${model.tripId}`);
  const covering = asked ? stayOn(model, asked) : null;
  const planned = asked ? (covering && covering.placeId === place.id ? covering : null) : model.nights.find((n) => n.placeId === place.id) || null;
  const day = planned ? findDay(model, { dayId: planned.startDayId }) : asked;
  if (!day || !day.date) throw new MessageError(`"${place.name}" is not a planned night with a date: give dayNumber, the evening of the night`);
  const nights = Math.max(1, Math.min(30, a.nights || (planned ? planned.nights : 1)));
  const endDay = model.days[day.index + nights];
  const endDate = nights > 1 ? (endDay && endDay.date) || new Date(Date.parse(`${day.date}T12:00:00Z`) + nights * 864e5).toISOString().slice(0, 10) : null;
  // Arrival: the night's planned time in the day, else its check-in.
  let arrival = a.arrival || null;
  if (!arrival && planned) {
    const asg = day.assignments.find((x) => x.accommodationId === planned.id);
    const m = asg && asg.place.time != null ? asg.place.time : null;
    arrival = m != null ? hhmm(m) : planned.checkIn || null;
  }
  const info = place.info;
  // The price asked to confirm is the one the plan counts: the whole party, the whole stay
  // (per person x travellers, dog fee, a flat price once). Unknown when the unit is not a
  // night's (per hour, per entry): then the host is asked for it.
  const priceN = placeInfo.nightCost(place.price, info, settings, nights).perStay;
  const base = {
    start: day.date, end: endDate, nights, travellers: settings.travellers || 2, dog: !!settings.dog, vehicle: settings.vehicle,
    length: settings.vehicle_length_m, height: settings.vehicle_height_m,
    time: arrival, price: priceN, currency: placeInfo.currencyOf(place.raw, model.currency), signature: a.signature ? String(a.signature).slice(0, 80) : null,
  };
  const keys = questionsFor(info, settings, { arrival, price: priceN });
  const extraQ = (a.extra_questions || []).map((x) => String(x).slice(0, 200)).slice(0, 5);
  const known = langsOf();
  const mine = known.includes(settings.language) ? settings.language : null;
  const langs = [...new Set(['en', mine, known.includes(a.language_extra) ? a.language_extra : null].filter(Boolean))];
  const parts = langs.map((lg) => body(lg, keys, params(lg, base), extraQ));
  const text = parts.join(`\n\n${SEPARATOR}\n\n`);
  const routes = contacts.channels(contacts.reachOf(info, place.raw));
  const booking = planned ? nightStatus.reservationFor(planned, model.reservations) : nightStatus.candidateReservation(model.reservations, place.id, day.id);
  const status = nightStatus.statusOf(booking);
  // The date in the user's own language (English when the user's is not a message language).
  const dateShort = new Intl.DateTimeFormat(LOCALE[mine || 'en'], { day: '2-digit', month: '2-digit', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${day.date}T12:00:00Z`));
  const subject = `${langs.map((lg) => TEXT[lg].subject).join(' / ')} — ${dateShort}${nights > 1 ? ` (${nights})` : ''}`;
  return {
    placeId: place.id, place: place.name, date: day.date, nights,
    to: routes[0] ? { ...routes[0], name: (info && info.contacts.contact_name) || place.name } : null,
    otherChannels: routes.slice(1),
    ...(routes.length ? {} : { noContact: 'No e-mail, phone or website known for this place: find the official contact first (vanlife_place with fill, or the official site), and record it with vanlife_place set.contacts.' }),
    languages: (info && info.contacts.languages && info.contacts.languages.length) ? info.contacts.languages : null,
    subject,
    text,
    languages_used: langs,
    questions: keys.map((k) => Object.fromEntries([['key', k], ...langs.map((lg) => [lg, fill(TEXT[lg][k], params(lg, base))])])).concat(extraQ.map((x) => ({ key: 'extra', en: x }))),
    // The status the night has now: the reminder never asks to step a booked night back.
    nightStatus: status,
    reminder: `DRAFT ONLY. Show this exact text to the user and wait for their explicit validation before it is sent; the user sends it, or tells you to. It is a request for information, not a booking. Once sent, record it with vanlife_place log (direction "sent")${status === 'spotted' || status === 'dropped' ? ' and vanlife_night set status "contacted"' : ` (the night is already "${status}": leave its status as it is)`}.`,
  };
}

module.exports = { draft, questionsFor, TEXT, SEPARATOR, langsOf, MessageError };
